### ISSUE TITLE
adaptation for mobile

### ISSUE THREAD

**Issue by wey-gu** [OldPanda/green-tiles#7]
nice job!

![583F360D-E58D-4BFE-A174-35D403D38363](https://user-images.githubusercontent.com/1651790/218244154-7c40b3b6-d3a8-4ade-95c3-4261bdf08742.png)

**Comment by OldPanda** [comment]
Thanks for raising the issue!

**Comment by OldPanda** [comment]
Updated UI on mobile devices by https://github.com/OldPanda/green-tiles/pull/10
